In [1]:
# 정수형 series만들기
import pandas as pd
s=pd.Series([1,2,3,4,8])
print(s)

0    1
1    2
2    3
3    4
4    8
dtype: int64


In [2]:
# 정수형  series
s = pd.Series([1,3,2,5,3,6,2,3,1,2])
print(s)

0    1
1    3
2    2
3    5
4    3
5    6
6    2
7    3
8    1
9    2
dtype: int64


In [3]:
# 실수형  series
s = pd.Series([1,2,5,3,8,9,7])
print(s)

0    1
1    2
2    5
3    3
4    8
5    9
6    7
dtype: int64


In [14]:
# 인덱스 지정 
s = pd.Series([1,2,5,3,8], index=['a', 'b', 'c', 'd', 'e'])
print(s)

a    1
b    2
c    5
d    3
e    8
dtype: int64


In [8]:
import numpy as np
a = np.array([1,2,3])
print(a)
b = np.zeros(5)
print(b)
c = np.ones((2,3))
print(c)

[1 2 3]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])
# 요소별 합
print(np.add(a, b))
# 요소별 곱
print(np.multiply(a, b))
# 어레이 값의 평균 
print(np.mean(b))



[5 5 5 5]
[4 6 6 4]
2.5


In [16]:
# 0과 1사이에서 균일한 분포를 갖는 숫자 샘플형 
a = np.random.rand(2,5)
print(a)

# 표준정규분포를 갖는 숫자들 샘플링
b = np.random.randn(2,4)
print(b)


[[0.77752841 0.68834703 0.15973385 0.81324119 0.30684501]
 [0.60300233 0.47043917 0.34753018 0.38761449 0.87718077]]
[[ 0.2429745   0.99711603 -0.9449383  -0.45154583]
 [-0.47249681  0.35231381  0.53793617  0.58683853]]


In [19]:
# 파이 
a = np.pi
print(a)
#오일러상수
b = np.e
print(b)

3.141592653589793
2.718281828459045


In [21]:
a = np.array([1,2,5,6,8])
print(type(a))
print(a)
print(a.dtype)

<class 'numpy.ndarray'>
[1 2 5 6 8]
int32


In [24]:
a = np.array([[1,2,3,4],[1,2,3,4]])
print(a)

[[1 2 3 4]
 [1 2 3 4]]


In [25]:
# 타입지정
# dtype = 요소들의 자료형을 알고 싶을때. 
a = np.array(([1,2,3],[4,5,6]),dtype = complex)
print(a)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [33]:
print(np.zeros(10))
b = np.ones((2,3,4), dtype = np.int16)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [39]:
no = [1,2,3]
subjname = []
subjname.append('수학')
subjname.append('과학')
subjname.append('파이썬')
subject = pd.DataFrame()
subject['과목번호'] = no
subject['과목명'] = subjname
print(subject)
subject.to_excel("C:\py_text2\subject.xlsx", index=False)

   과목번호  과목명
0     1   수학
1     2   과학
2     3  파이썬


In [42]:
subject.to_csv("C:\py_text2\subject.csv", encoding='utf-8-sig',index=True)

In [49]:
#데이터프레임은 파이썬의 리스트와 딕셔너리의 조합이다. 
df = pd.DataFrame({"이름":["홍길동", "홍길순", "임꺽정"],"age":[20,50,32], "성별":["male","female","male"]})
print(df)
#데이터 프레임에서 성별컬럼만 출력
print(df["성별"])
#데이터프레임에 고향컬럼 추가 
home = pd.Series(["서울", "부산", "대전"], name = "고향")
df["고향"] = home 
#집계함수 
#평균, 최대값, 최소값
print(df["age"].mean())
print(df["age"].max())
print(df["age"].min())


    이름  age      성별
0  홍길동   20    male
1  홍길순   50  female
2  임꺽정   32    male
0      male
1    female
2      male
Name: 성별, dtype: object
34.0
50


In [52]:
df = pd.DataFrame({"이름":["홍길동", "홍길순", "임꺽정"],"age":[20,50,32], "성별":["male","female","male"]})
#데이터 프레임의 기본 통계 내용을 출력 
print(df.describe())
print(df.head(2))
#head는 위에서부터 데이터를 끊어온다,. 
print(df.head(2))
#tail은 밑에서부터 데이터를 끊어온다
print(df.tail(2))


             age
count   3.000000
mean   34.000000
std    15.099669
min    20.000000
25%    26.000000
50%    32.000000
75%    41.000000
max    50.000000
    이름  age      성별
0  홍길동   20    male
1  홍길순   50  female
    이름  age      성별
0  홍길동   20    male
1  홍길순   50  female
    이름  age      성별
1  홍길순   50  female
2  임꺽정   32    male


In [65]:
df = pd.read_excel("order.xlsx")
print(df)
# 1. 손흥민이 주문한 갯수는?
is_son = df["name"] == "손흥민"
print(df[is_son]["order_no"].count())
# 2. 손흥민이 산 상품은?
print(df[is_son]["product"])
# 3. 스커트를 산 사람은?
is_skirt = df["product"] == "스커트"
print(df[is_skirt]["name"])
# 4. 김지원이 사용한 총 금액은?
is_kim = df["name"] == "김지원"
print(df[is_kim].sum())
# 5. 가장많이 주문한 사람의 아이디와 이름, 주문횟수는?
newdf = df.groupby(["user_id","name"])["order_no"].count().reset_index(name = "count")
newdf = newdf.sort_values("count", ascending = False) #false 내림차순 true 오름차순

   Unnamed: 0  order_no user_id user_pass name address product    price  brand
0           0         1   user1     pass1  손흥민      런던     운동화   100000    나이키
1           1         2   user2     pass2   설현      서울      코트   150000    버버리
2           2         3   user3     pass3   원빈      대전     반바지    30000   유니클로
3           3         4   user4     pass4  송혜교      대구     스커트    55000     자라
4           4         5   user5     pass5  소지섭      부산      코트  1100000   알레그리
5           5         6   user6     pass6  김지원      울산     티셔츠     9900   지오다노
6           6         7   user6     pass6  김지원      울산     운동화   220000     텐디
7           7         8   user1     pass1  손흥민      런던     스커트    30000  크로커다일
8           8         9   user1     pass1  손흥민      런던      코트   580000    띠어리
3
0    운동화
7    스커트
8     코트
Name: product, dtype: object
3    송혜교
7    손흥민
Name: name, dtype: object
Unnamed: 0            11
order_no              13
user_id       user6user6
user_pass     pass6pass6
name    