In [1]:
# 정수형 series만들기
import pandas as pd
s=pd.Series([1,2,3,4,8])
print(s)

0    1
1    2
2    3
3    4
4    8
dtype: int64


In [2]:
# 정수형  series
s = pd.Series([1,3,2,5,3,6,2,3,1,2])
print(s)

0    1
1    3
2    2
3    5
4    3
5    6
6    2
7    3
8    1
9    2
dtype: int64


In [3]:
# 실수형  series
s = pd.Series([1,2,5,3,8,9,7])
print(s)

0    1
1    2
2    5
3    3
4    8
5    9
6    7
dtype: int64


In [14]:
# 인덱스 지정 
s = pd.Series([1,2,5,3,8], index=['a', 'b', 'c', 'd', 'e'])
print(s)

a    1
b    2
c    5
d    3
e    8
dtype: int64


In [8]:
import numpy as np
a = np.array([1,2,3])
print(a)
b = np.zeros(5)
print(b)
c = np.ones((2,3))
print(c)

[1 2 3]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])
# 요소별 합
print(np.add(a, b))
# 요소별 곱
print(np.multiply(a, b))
# 어레이 값의 평균 
print(np.mean(b))



[5 5 5 5]
[4 6 6 4]
2.5
